services:
  postgres:
    image: postgres:15
    container_name: spotify_pg
    environment:
      POSTGRES_USER: imad
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spotify_dw
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.9.1
    container_name: airflow_webserver
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://imad:password@postgres:5432/spotify_dw
      - AIRFLOW__WEBSERVER__SECRET_KEY=mysecretkey
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./.env:/opt/airflow/.env
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.1
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - airflow-webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://imad:password@postgres:5432/spotify_dw
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./.env:/opt/airflow/.env
    command: scheduler

volumes:
  pg_data:

  airflow_logs:
