version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: spotify_pg
    environment:
      POSTGRES_USER: imad
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spotify_dw
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
